name: 'Terraform GitHub Actions'
on:
   - pull_request
   - push
jobs:
  terraform:
      name: 'Terraform'
      runs-on: ubuntu-latest
      steps:
         - name: 'Checkout'
           uses: actions/checkout@master
         - name: 'Terraform Format'
           uses: hashicorp/terraform-github-actions@master
           with:
             tf_actions_version: 1.1.9
             tf_actions_subcommand: 'apply'
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


