name: 'GitHub Actions'
on:
   - pull_request
   - push
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: setup terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
          unzip terraform_0.12.24_linux_amd64.zip
          sudo mv terraform /usr/bin/
          terraform version
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master 
        with:
          tf_actions_working_dir: ./terraform_git/scripts/templates/gcp
          tf_actions_version: 1.1.9
          tf_actions_subcommand: 'init'
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.1.9
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ./terraform_git/scripts/templates/gcp
        env:
          TF_CLI_ARGS_apply: '-var-file "../cluster_config/dev/terraform.gcpvars" -auto-approve'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

