name: 'Terraform GitHub Actions'
on:
   - pull_request
   - push
jobs:
  terraform:
      name: 'Terraform'
      runs-on: ubuntu-latest
      steps:
         - name: 'Checkout'
           uses: actions/checkout@v2
         - name:  'Setup Terraform'
           uses: hashicorp/setup-terraform@v1
         - name: 'Terraform Init'
   #        uses: hashicorp/terraform-github-actions@master 
           with:
             tf_actions_version: 1.1.9
             run: |
               cd "terraform_git/scripts/templates/gcp"
             tf_actions_subcommand: 'init'
         - name: 'Terraform Apply'
    #       uses: hashicorp/terraform-github-actions@master
           with:
             tf_actions_version: 1.1.9
             run: |
               cd "terraform_git/scripts/templates/gcp"
             tf_actions_subcommand: 'apply'
           env:
             TF_CLI_ARGS_apply: '-var-file "terraform_git/scripts/templates/cluster_config/dev/terraform.gcpvars" -auto-approve'
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


